### ISSUE TITLE
important --replay attack --chainId need check

### ISSUE THREAD

**Issue by vchain007** [vision-consensus/vision-core#106]
compatible with ethereum transaction

chainId need check
 assume that a user have eth/vs on both ethereum and vision. if user a transfer 100 eth to user b  on ethereum . user b can get trx rlpdata and replay attack ,user lose 100 vs on vision not for his will

**Comment by darylccc** [comment]
We have made de-duplication judgments on Ethereum-compatible transactions. For details, please check the linked PR.

**Comment by vchain007** [comment]
ok pretty good
