### ISSUE TITLE
 ETH compatible issues

### ISSUE THREAD

**Issue by theway001** [vision-consensus/vision-core#111]
1. under rlpParseToTriggerSmartContract redo parse CallValue
2. under rlpParseToDeployContract redo parse CallValue
3. under rlpParseToDeployContract the OriginEntropyLimit should be fixed

**Comment by vchain007** [comment]
4.can ethereum compatible tranaction make  security vulnerability by  vision multi sign ? need delibrate check

**Comment by darylccc** [comment]
We have optimized the verification logic of multi-signatures, and optimized the parsing of contract parameters. 
eg:
`
      smartBuilder
              .setAbi(abiBuilder)
              .setBytecode(ByteString.copyFrom(this.data))
              .setCallValue(ByteUtil.byteArrayToLongDividePrecision(this.value, "1000000000000")) // transfer to contract
              .setConsumeUserResourcePercent(100)
              .setOriginEntropyLimit(ByteUtil.byteArrayToLong(gasLimit));
`
Thanks for the suggestion, please stay tuned for further updates.
