### ISSUE TITLE
Fullnode support Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by johntailor1** [vision-consensus/vision-core#2]
I want to use the connection through my node on the front. I run my node on the ovh server with this command:

"nohup java -Xmx24g -XX:+HeapDumpOnOutOfMemoryError -jar FullNode.jar -c config.conf </dev/null &>/dev/null &"

But from the front I can not connect to my node, swears at Access-Control-Allow-Origin.

How can I start a node so that I can connect from the front ?

**Comment by vchain007** [comment]
done
